### ISSUE TITLE
Not supporting the Russian language.

### ISSUE THREAD

**Issue by FoxCookie123** [AvacadoWizard120/Censor-Chat#1]
Not supporting the Russian language.
I am facing such a problem that the mod replaces * only English speech. This is not the case with Russians.
And I wanted to know if this is a bug or how it should be?
If this is how it should be, then please add a function to support Russian and other languages.

**Comment by AvacadoWizard120** [comment]
Would mind using Google translate to rewrite your bug report? 🙏🏽

**Comment by FoxCookie123** [comment]
I used Google Translate to write to you about this problem or about a way to improve the mod.
Did I state the problem incorrectly or did you not understand the language in which I wrote?

**Comment by AvacadoWizard120** [comment]
I understand that the mod doesn't work with the Russian alphabet, however... I wouldn't know why. It shouldn't matter what language you use as long as you're modifying the confit properly.

**Comment by FoxCookie123** [comment]
{
  "deleteMessage": false,
  "blacklist": [
    "badword1",
    "wrong",
    "你好",
    "Привет"
  ],
  "repeatCharForLengthOfWord": false,
  "customChar": false,
  "replaceWith": "*",
  "repeatChar": 1
}

This is what my config looks like. It recognizes and removes only the first 2 words. He leaves the rest despite the fact that they are on the list.

**Comment by AvacadoWizard120** [comment]
I will look into this and see what is going on.

**Comment by AvacadoWizard120** [comment]
Tell me what mod loader you are using

**Comment by FoxCookie123** [comment]
Fabric 1.20.4. Версия Fabric loader 0.15.11
